### ISSUE TITLE
Model Weight License 

### ISSUE THREAD

**Issue by shiv203** [facebookresearch/sscd-copy-detection#12]
The repo is currently shared under mit license. It is also explicitly mentioned that the code base is in mit license. There are also some trained model weights shared in this repo. it would be kind of you to clarify if the weights also comes under the same license.

Thanks

**Comment by edpizzi** [comment]
Thanks for the question! The entire project, including model weights, is licensed under the MIT license.

**Comment by shiv203** [comment]
Thanks for the clarification.

Thanks.
