### ISSUE TITLE
Preparation of the dataset

### ISSUE THREAD

**Issue by zcgit001** [facebookresearch/sscd-copy-detection#8]
Thank you for your work. But I have some questions about the preparation of the dataset. For example, how do I need to get the file “val_groundtruth_matches.csv” in disc.py 44 line？

**Comment by WangWenhao0716** [comment]
https://ai.facebook.com/datasets/disc21-dataset/

**Comment by edpizzi** [comment]
Thanks @WangWenhao0716 for answering. I'm going to mark this as closed, but @zcgit001, let me know if you're unable to access the dataset.
